# Generated by Django 2.0.6 on 2018-06-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
