# Generated by Django 2.0.6 on 2018-06-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=128)),
                ('doc_name', models.CharField(max_length=128)),
                ('appt_date', models.DateField()),
                ('appt_time', models.TimeField()),
            ],
        ),
    ]
