# Generated by Django 2.0.6 on 2018-06-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20180609_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doc_name',
            field=models.CharField(max_length=100),
        ),
    ]
